# Generated by Django 4.0.5 on 2022-07-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pole',
            name='purchased_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='checkout',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='due',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
