# Generated by Django 4.0.6 on 2022-07-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poles', '0002_alter_pole_purchased_at_alter_rental_checkout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pole',
            old_name='purchased_at',
            new_name='purchase_date',
        ),
        migrations.AddField(
            model_name='pole',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pole',
            name='functional',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pole',
            name='material',
            field=models.CharField(choices=[('CF', 'Carbon Fiber'), ('FG', 'Fiberglass')], default='FG', max_length=2),
        ),
    ]
